{if (!empty($news))}
    <div class="news-detail-wrapper">
        <p class="news-title">{echo $news->title}</p>
        <p class="news-created">{echo $news->created} {echo $news->author}</p>
        {echo html_entity_decode($news->body)}
        <br />
    </div>
    <div class="news-fblikebtn">
        <iframe src="//www.facebook.com/plugins/like.php?href={echo $news->fbLikeUrl}&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=21" 
            scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:21px;" allowTransparency="true"></iframe>

        <div class="fb-share-button" data-layout="button-count" data-href="{echo $news->fbLikeUrl}"></div>
    </div>
{/if}