<h1 class="visuallyhidden">Novinky</h1>
{if !empty($newsbatch)}
    {foreach $news in $newsbatch}
        <div class="news-wrapper">
            <p>
                <a href="#" class="ajaxLink news-title" id="show_news-detail_{echo $news->urlKey}">{echo $news->title}</a>
            </p>
            <p class="news-created">{echo $news->created}</p>
            {echo html_entity_decode($news->shortBody)}
            <br>
        </div>
    {/foreach}
{/if}{else}
    <p class="center message-empty">Žádné novinky</p>
{/else}
<script type="text/javascript" src="/public/js/custom/newsloaddetail.js"></script>