{if !empty($newsbatch)}
{foreach $news in $newsbatch}
<div class="oneNews">
    <p>
        <a href="#" class="ajaxLink newsTitle" id="show_news-detail_{echo $news->urlKey}">{echo $news->title}</a>
    </p>
    <p class="newsAdded">{echo $news->created}</p>
    {echo html_entity_decode($news->shortBody)}
    <br>
</div>
{/foreach}
{/if}
<script type="text/javascript" src="/public/js/custom/newsloaddetail.js"></script>