<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/video/">Videos List</a></li>
    <li><a href="/admin/video/add/">Add Video</a></li>
    <li class="current"><a href="#">Edit Video</a></li>
</ul>

<div class="content">
    <div class="contenttitle"><h2 class="form"><span>Video Informations</span></h2></div><br />
    <form class="stdform stdform2" method="post" action="#">
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        <p>
            <label>Title</label>
            <span class="field">
                <input type="text" name="title" class="longinput" value="{echo $video->title}"/>
                {if isset($errors["title"])}
                <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>URL</label>
            <span class="field">
                <input type="text" name="path" class="longinput" value="{echo $video->path}"/>
                {if isset($errors["path"])}
                <label class="error">{echo join("<br/>", $errors["path"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Video Width<small>(Recommended 500)</small></label>
            <span class="field">
                <input type="text" name="video_w" class="longinput" value="{echo $video->width}"/>
                {if isset($errors["video_w"])}
                <label class="error">{echo join("<br/>", $errors["video_w"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Video Height<small>(Recommended 281)</small></label>
            <span class="field">
                <input type="text" name="video_h" class="longinput" value="{echo $video->height}"/>
                {if isset($errors["video_h"])}
                <label class="error">{echo join("<br/>", $errors["video_h"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Section</label>
            <span class="field">
                {foreach $section in $sections}
                    {script $s = ""}
                        {if in_array($section->title, $video->inSections)}
                            {script $s = "checked=\"checked\""}
                        {/if}
                <span class="labeled-checkbox">
                    <input type="checkbox" name="sections[]" {echo $s} value="{echo $section->id}">{echo ucfirst($section->title)}
                </span>
                {/foreach}
                {if isset($errors["sections"])}
                <label class="error">{echo join("<br/>", $errors["sections"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Active</label>
            <span class="field">
                <select name="active" class="longinput">
                    {if $video->active}
                    <option value="0">Inactive</option>
                    <option value="1" selected>Active</option>
                    {/if}
                    {else}
                    <option value="0" selected>Inactive</option>
                    <option value="1">Active</option>
                    {/else}
                </select>
            </span>
        </p>
        <p>
            <label>Priority<small>5 = highest priority</small></label>
            <span class="field">
                <select name="priority" >
                    {for $i=0 $i<6 $i++}
                    {if $i == $video->priority}
                    <option value="$i" selected="selected">{echo $i}</option>
                    {/if}
                    {else}
                    <option value="$i">{echo $i}</option>
                    {/else}
                    {/for}
                </select>
            </span>
        </p>
        <p class="stdformbutton">
            <input name="submitEditVideo" type="submit" value="Save" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>
<br clear="all" />