<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/partner/">All Partners</a></li>
    {if $isAdmin}<li><a href="/admin/partner/sections/">Partner Sections</a></li>{/if}
    <li><a href="/admin/partner/add/">Add Partner</a></li>
    <li class="current"><a href="#">Edit Partner</a></li>
</ul>

<div class="content">
    <div class="contenttitle">
        <h2 class="form"><span>Partner Informations</span></h2>
    </div>
    
    <form class="stdform stdform2" method="post" action="#" enctype="multipart/form-data">
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        
        <input type="hidden" name="MAX_FILE_SIZE" value="5000000"/>
        <p>
            <label>Partner name*</label>
            <span class="field">
                <input type="text" name="title" class="longinput" value="{echo $partner->title}"/>
                {if isset($errors["title"])}
                    <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Logo*</label>
            {if $partner->logo != ""}
            <span class="field" id="currentLogo">
                <img src="{echo $partner->logo}" alt="" height="100px" />
                <a href="#" value="{echo $partner->id}" id="delLogo" class="btn btn3 btn_trash" title="Delete logo"></a>
            </span> 
            
            <span class="field nodisplay" id="uploadLogo" >
                <input type="file" name="logo" />
                {if isset($errors["logo"])}
                    <label class="error">{echo join("<br/>", $errors["logo"])}</label>
                {/if}
            </span>
            {/if}
            {else}
            <span class="field" id="uploadLogo">
                <input type="file" name="logo" />
                {if isset($errors["logo"])}
                    <label class="error">{echo join("<br/>", $errors["logo"])}</label>
                {/if}
            </span> 
            {/else}
        </p>
        <p>
            <label>Address</label>
            <span class="field">
                <textarea rows="10" name="address" class="longinput">{echo $partner->address}</textarea>
                {if isset($errors["address"])}
                    <label class="error">{echo join("<br/>", $errors["address"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Webpage*</label>
            <span class="field">
                <input type="text" name="web" class="longinput" value="{echo $partner->web}"/>
                {if isset($errors["web"])}
                    <label class="error">{echo join("<br/>", $errors["web"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Email</label>
            <span class="field">
                <input type="text" name="email" class="longinput" value="{echo $partner->email}"/>
                {if isset($errors["email"])}
                    <label class="error">{echo join("<br/>", $errors["email"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Mobile</label>
            <span class="field">
                <input type="text" name="mobile" class="longinput" value="{echo $partner->mobile}"/>
                {if isset($errors["mobile"])}
                    <label class="error">{echo join("<br/>", $errors["mobile"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Section</label>
            <span class="field">
                <select name="section" class="longinput">
                    {foreach $section in $sections}
                        {script $s=""}
                        {if $section->id == $partner->sectionId}
                            {script $s = "selected"}
                        {/if}
                        <option value="{echo $section->id}" {echo $s}>{echo $section->title}</option>
                    {/foreach}
                </select>
            </span>
        </p>
        <p>
            <label>Active</label>
            <span class="field">
                <select name="active" class="longinput">
                    {if $partner->active}
                    <option value="0">Inactive</option>
                    <option value="1" selected>Active</option>
                    {/if}
                    {else}
                    <option value="0" selected>Inactive</option>
                    <option value="1">Active</option>
                    {/else}
                </select>
            </span>
        </p>

        <p class="stdformbutton">
            <input name="submitEditPartner" type="submit" value="Save" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>
<br clear="all" />