<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/partner/">All Partners</a></li>
    <li><a href="/admin/partner/sections/">Partner Sections</a></li>
    <li><a href="/admin/partner/add/">Add Partner</a></li>
    <li class="current"><a href="#">Edit Partner Section</a></li>
</ul>

<div class="content">
    <div class="contenttitle">
        <h2 class="form"><span>Partner Section Informations</span></h2>
    </div>
    
    <form class="stdform stdform2" method="post" action="#">
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
        <p>
            <label>Section title*</label>
            <span class="field">
                <input type="text" name="title" class="longinput" value="{echo $section->title}"/>
                {if isset($errors["title"])}
                    <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Url Key*</label>
            <span class="field">
                <input type="text" name="urlkey" class="longinput" value="{echo $section->urlKey}"/>
                {if isset($errors["urlKey"])}
                    <label class="error">{echo join("<br/>", $errors["urlKey"])}</label>
                {/if}
            </span> 
        </p>
        <p>
            <label>Rank</label>
            <span class="field">
                <input type="text" name="rank" class="longinput" value="{echo $section->rank}"/>
                {if isset($errors["rank"])}
                    <label class="error">{echo join("<br/>", $errors["rank"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Active</label>
            <span class="field">
                <select name="active" class="longinput">
                    {if $section->active}
                    <option value="0">Inactive</option>
                    <option value="1" selected>Active</option>
                    {/if}
                    {else}
                    <option value="0" selected>Inactive</option>
                    <option value="1">Active</option>
                    {/else}
                </select>
            </span>
        </p>

        <p class="stdformbutton">
            <input name="submitEditPartnerSection" type="submit" value="Save" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>
<br class="clear-all" />