<div class="section-content-collection">
    {if (!empty($collections))}
        {foreach $collection in $collections}
        <p class="collectionTitle">
            {echo $collection->title." ".$collection->date} / fotograf {echo $collection->photographer}
        </p>
        <div class="section-content-photos">
            {if (!empty($photos = $collection->photos))}
                {foreach $photo in $photos}
                    <a href="{echo $photo->path}" class="highslide" 
                            title="{echo $photo->photoName}" onclick="return hs.expand(this, configcollection)">
                        <img src="{echo $photo->thumbPath}" height="140px" alt="Marko.in" title="{echo $photo->photoName}"/>
                    </a>
                {/foreach}
            {/if}
            {else}
                <p class="messageEmpty">K dispozici nejsou žádné fotografie</p>
            {/else}
            </div>
            <br/><hr/><br/>
        {/foreach}

        <div class="section-content-videos">
            {if (!empty($videos = $collection->videos))}
                <p class="collectionTitle">Single 2013 - Hoříš</p><br/>
                {foreach $video in $videos}
                    <iframe width="{echo $video->width}" height="{echo $video->height}" 
                        src="{echo $video->path}" frameborder="0" allowfullscreen></iframe>
                {/foreach}
            {/if}
        </div>
    {/if}
    {else}
        <p class="messageEmpty">Žádné kolekce</p>
    {/else}
</div>