<div class="section-content-collection">
    {if ($collecarr && !empty($collecarr))}
        {foreach $collection in $collecarr}
            <p class="collectionTitle">
                {echo $collection->title." ".$collection->date} / fotograf {echo $collection->photographer}
            </p>
            <div class="section-content-photos">
                {script $colphotos=$collection->photos}
                {if !empty($colphotos)}
                    {foreach $photo in $colphotos}
                        <a href="{echo $photo->path}" class="highslide" 
                                title="{echo $photo->photoName}" onclick="return hs.expand(this, configcollection)">
                            <img src="{echo $photo->thumbPath}" height="140px" alt="Marko.in" title="{echo $photo->photoName}"/>
                        </a>
                    {/foreach}
                {/if}
                {else}
                    <p class="messageEmpty">K dispozici nejsou žádné fotografie</p>
                {/else}
            </div>
             <br/><hr/><br/>

            <div class="section-content-videos">
                {script $colvideos=$collection->videos}
                {if !empty($colvideos)}
                    {foreach $video in $colvideos}
                        <iframe width="{echo $video->width}" height="{echo $video->height}" 
                            src="{echo $video->path}" frameborder="0" allowfullscreen></iframe>
                    {/foreach}
                {/if}
            </div>
           
        {/foreach}
    {/if}
    {else}
        <p class="messageEmpty">Žádné kolekce</p>
    {/else}
</div>