<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/collection/">Collection List</a></li>
    <li><a href="/admin/collection/add/">Add Collection</a></li>
    <li><a href="/admin/collection/detail/{echo $collection->id}">Collection Detail</a></li>
    <li class="current"><a href="#">Add Video</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle">
        <h2 class="form"><span>Video Informations</span></h2>
    </div>
    <form class="stdform stdform2" method="post" action="#">
        <input type="hidden" name="tk" value="{echo $token}" />
        <p>
            <label>Title</label>
            <span class="field">
                <input type="text" name="title" class="longinput" value="{echo isset($video)? $video->title: ""}"/>
                {if isset($errors["title"])}
                <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>URL</label>
            <span class="field">
                <input type="text" name="path" class="longinput" value="{echo isset($video)? $video->path: ""}"/>
                {if isset($errors["path"])}
                <label class="error">{echo join("<br/>", $errors["path"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Video Width<small>Recommended 500</small></label>
            <span class="field">
                <input type="text" name="video_w" class="longinput" value="{echo isset($video)? $video->width: ""}"/>
                {if isset($errors["width"])}
                <label class="error">{echo join("<br/>", $errors["width"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Video Height<small>Recommended 281</small></label>
            <span class="field">
                <input type="text" name="video_h" class="longinput" value="{echo isset($video)? $video->height: ""}"/>
                {if isset($errors["height"])}
                <label class="error">{echo join("<br/>", $errors["height"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Priority<small>5 = highest priority</small></label>
            <span class="field">
                <select name="priority" >
                    <option value="0">0</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </span>
        </p>
        <p class="stdformbutton">
            <input name="submitAddVideo" type="submit" value="Save" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>
<br clear="all" />