<ul class="maintabmenu">
    <li class="current"><a href="/admin/analytics">Analytics - Week</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="one_half">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Visits - Evolution Graph</span></h2></div>
            <div class="widgetcontent">
                <iframe width="100%" height="350px" src="http://marko.in/piwik/index.php?module=Widgetize&action=iframe&columns[]=nb_visits&widget=1&moduleToWidgetize=VisitsSummary&actionToWidgetize=getEvolutionGraph&idSite=1&period=week&date=yesterday&disableLink=1&widget=1&token_auth=3a3c2653e07ec402b1dc1983b8974c95" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->
    </div><!--one_half-->

    <div class="one_half last">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Visitor Location</span></h2></div>
            <div class="widgetcontent">
                <iframe width="100%" height="350px" src="http://marko.in/piwik/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=UserCountry&actionToWidgetize=getCountry&idSite=1&period=week&date=yesterday&disableLink=1&widget=1&token_auth=3a3c2653e07ec402b1dc1983b8974c95" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->                        
    </div><!--one_half-->

    <br class="clear-all" /><br />

    <div class="one_half">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Visits - Live</span></h2></div>
            <div class="widgetcontent" >
                <iframe width="100%" height="500px" src="http://marko.in/piwik/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=Live&actionToWidgetize=widget&idSite=1&period=week&date=yesterday&disableLink=1&widget=1&token_auth=3a3c2653e07ec402b1dc1983b8974c95" scrolling="auto" frameborder="0" marginheight="0" marginwidth="0"></iframe>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->

    </div><!--one_half-->

    <div class="one_half last">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Visit duration</span></h2></div>
            <div class="widgetcontent">
                <iframe width="100%" height="500px" src="http://marko.in/piwik/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=VisitorInterest&actionToWidgetize=getNumberOfVisitsPerVisitDuration&idSite=1&period=week&date=yesterday&disableLink=1&widget=1&token_auth=3a3c2653e07ec402b1dc1983b8974c95" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->                        
    </div><!--one_half-->

    <br class="clear-all" /><br />

    <div class="one_half">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Browser version</span></h2></div>
            <div class="widgetcontent">
                <iframe width="100%" height="350px" src="http://marko.in/piwik/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=UserSettings&actionToWidgetize=getBrowserVersion&idSite=1&period=week&date=yesterday&disableLink=1&widget=1&token_auth=3a3c2653e07ec402b1dc1983b8974c95" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>                
            </div><!--widgetcontent-->
        </div><!--widgetbox-->

    </div><!--one_half-->
    <div class="one_half last">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>User screen resolution</span></h2></div>
            <div class="widgetcontent">
                <iframe width="100%" height="350px" src="http://marko.in/piwik/index.php?module=Widgetize&action=iframe&widget=1&moduleToWidgetize=UserSettings&actionToWidgetize=getResolution&idSite=1&period=week&date=yesterday&disableLink=1&widget=1&token_auth=3a3c2653e07ec402b1dc1983b8974c95" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>            
            </div><!--widgetcontent-->
        </div><!--widgetbox-->                        
    </div><!--one_half-->

    <br class="clear-all" /><br />
    
</div><!--content-->