<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/news/">News List</a></li>
    <li><a href="/admin/news/add/">Add News</a></li>
    <li class="current"><a href="#">Edit News</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="two_third">
        <div class="widgetbox">
            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>News content</span></h2>
            </div><!--contenttitle-->

            <form class="stdform stdform2" method="post" action="#" >
                <input type="hidden" name="tk" id="tk" value="{echo $token}" />
                <p>
                    <label>Title</label>
                    <span class="field">
                        <input type="text" name="title" value="{echo $news->title}" />
                        {if isset($errors["title"])}
                            <label class="error">{echo join("<br/>", $errors["title"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Author</label>
                    <span class="field">
                        <input type="text" name="author" class="longinput" value="{echo $authUser->getWholeName()}"/>
                    </span>
                </p>
                <p>
                    <label>URL key<small>Automaticaly created from title</small></label>
                    <span class="field">
                        <input type="text" name="urlkey" class="longinput" value="{echo $news->urlKey}" />
                        {if isset($errors["urlKey"])}
                            <label class="error">{echo join("<br/>", $errors["urlKey"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Expiration Date</label>
                    <span class="field">
                        <input type="text" name="expiration" class="longinput datepicker" 
                               value="{echo $news->expirationDate}"/>
                        {if isset($errors["expirationDate"])}
                            <label class="error">{echo join("<br/>", $errors["expirationDate"])}</label>
                        {/if}
                    </span>
                </p>
                <p>
                    <label>Text*<small>Max. 5000 characters</small></label>
                    <span class="field">
                        <textarea rows="20" name="text" id="ckeditor">{echo $news->body}</textarea>
                        {if isset($errors["body"])}
                            <label class="error">{echo join("<br/>", $errors["body"])}</label>
                        {/if}
                        <br/>
                        <button id="news-text-to-teaser">Copy to Teaser</button>
                        <button id="news-clear-text">Clear</button>
                    </span>
                </p>
                <p>
                    <label>Teaser*<small>Max. 1000 characters</small></label>
                    <span class="field">
                        <textarea rows="20" name="shorttext" id="ckeditor2">{echo $news->shortBody}</textarea>
                        {if isset($errors["shortBody"])}
                            <label class="error">{echo join("<br/>", $errors["shortBody"])}</label>
                        {/if}
                        <br/>
                        <button id="news-clear-teaser">Clear</button>
                        <button id="news-readmore-link">Add Read More link</button>
                    </span>
                </p>
                <p>
                    <label>Active</label>
                    <span class="field">
                        <select name="active" class="longinput">
                            {if $news->active}
                                <option value="0">Inactive</option>
                                <option value="1" selected>Active</option>
                            {/if}
                            {else}
                                <option value="0" selected>Inactive</option>
                                <option value="1">Active</option>
                            {/else}
                        </select>
                    </span>
                </p>
                <p>
                    <label>Rss feed text<small>Max. 2048 characters<br/>Text only</small></label>
                    <span class="field">
                        <textarea rows="10" name="feedtext" class="longinput" >{echo $news->rssFeedBody}</textarea>
                        {if isset($errors["rssFeedBody"])}
                            <label class="error">{echo join("<br/>", $errors["rssFeedBody"])}</label>
                        {/if}
                        <br/>
                    </span>
                </p>

                <p class="stdformbutton">
                    <input name="submitEditNews" type="submit" value="Save" class="submit radius2" />
                    <input type="reset" class="reset radius2" value="Reset" />
                </p>
            </form>
        </div>
    </div>

    <div class="one_third last">
        <div class="widgetbox">
            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>Photos</span></h2>
            </div><!--contenttitle-->
            <div class="news-photos">
                {if ($photos && !empty($photos))}
                    {foreach $photo in $photos}
                        <span class="news-photo">
                            <img src="{echo $photo->getThumbPath()}" alt="{echo $photo->getPhotoName()}" width="200px"/>
                            <button class="stdbtn img-to-text" value="{echo $photo->getId()}">To Text</button>
                            <button class="stdbtn img-to-teaser" value="{echo $photo->getId()}">To Teaser</button>
                        </span>
                    {/foreach}
                {/if}
            </div>
            <br clear="all"/>
            <div class="contenttitle radiusbottom0">
                <h2 class="table"><span>Videos</span></h2>
            </div><!--contenttitle-->
            <div class="news-videos">
                {if ($videos && !empty($videos))}
                    {foreach $video in $videos}
                        <span class="news-video">
                            <iframe width="200px" src="{echo $video->getPath()}" frameborder="0" allowfullscreen></iframe>
                            <button class="stdbtn video-to-text" value="{echo $video->getId()}">To Text</button>
                            <button class="stdbtn video-to-teaser" value="{echo $video->getId()}">To Teaser</button>
                        </span>
                    {/foreach}
                {/if}
            </div>
        </div>
    </div>
    <br clear="all"/>
</div>
<br clear="all"/>
<script type="text/javascript" src="/public/js/custom/news.js"></script>