<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">Announcements List</a></li>
    <li><a href="/admin/announcement/add/">Add Announcement</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Announcements List</span></h2>
    </div><!--contenttitle-->

    <input type="hidden" name="tk" id="tk" value="{echo $token}" />
    <table cellpadding="0" cellspacing="0" border="0" class="stdtable" >
        <colgroup>
            <col class="con0" /><col class="con1" />
            <col class="con0" /><col class="con1" />
        </colgroup>
        <thead>
            <tr>
                <th class="head0">Created</th><th class="head1">Title</th>
                <th class="head0">Teaser</th><th class="head1">&nbsp;</th>
            </tr>
        </thead>
        <tbody>

            {if (!empty($announcements))}
                {foreach $anc in $announcements}
                    {if ($anc->active)}
                            <tr class="rowActive">
                        {/if} 
                        {else}
                            <tr>
                        {/else}
                        <td>{echo $anc->getCreated()}</td>
                        <td>{echo $anc->getTitle()}</td>
                        <td>{echo substr($anc->getBody(), 0, 60) . "..."}</td>
                    <td>
                        <a href="/admin/announcement/edit/{echo $anc->getId()}" class="btn btn3 btn_pencil" title="Edit"></a> 
                        {if $isAdmin}
                        <a href="/admin/announcement/delete/{echo $anc->getId()}" class="btn btn3 btn_trash deleteRow" title="Delete"></a>
                        {/if}
                    </td>
                    </tr>
                {/foreach}
            {/if}
        </tbody>
    </table>
</div>
<br clear="all"/><br />