<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/collectionmenu/">Collection Menu List</a></li>
    <li><a href="/admin/collectionmenu/add/">Add Collection Menu Item</a></li>
    <li class="current"><a href="#">Edit Collection Menu List</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle"><h2 class="form"><span>Collection menu Item</span></h2></div><br />
    <form class="stdform stdform2" method="post" action="#">
        <input type="hidden" name="tk" value="{echo $token}" />
        <p>
            <label>Title*</label>
            <span class="field">
                <input type="text" name="title" class="longinput" value="{echo $clmenu->title}"/>
                {if isset($errors["title"])}
                <label class="error">{echo join("<br/>", $errors["title"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>URL Key*</label>
            <span class="field">
                <input type="text" name="urlkey" class="longinput" value="{echo $clmenu->urlKey}"/>
                {if isset($errors["urlKey"])}
                <label class="error">{echo join("<br/>", $errors["urlKey"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Custom name</label>
            <span class="field">
                <input type="text" name="custom" class="longinput" value="{echo $clmenu->customName}"/>
                {if isset($errors["customName"])}
                <label class="error">{echo join("<br/>", $errors["customName"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Section*</label>
           <span class="field">
                <select name="section" class="longinput">
                    {foreach $section in $sections}
                        {script $s=""}
                        {if $section->id == $clmenu->sectionId}
                            {script $s = "selected"}
                        {/if}
                        <option value="{echo $section->id}" {echo $s}>{echo $section->title}</option>
                    {/foreach}
                </select>
            </span>
        </p>
        <p>
            <label>Rank<small>Max. 99</small></label>
            <span class="field">
                <input type="text" name="rank" class="longinput" value="{echo $clmenu->rank}"/>
            </span>
        </p>
        <p>
            <label>Active</label>
            <span class="field">
                <select name="active" class="longinput">
                    {if $clmenu->active}
                    <option value="0">Inactive</option>
                    <option value="1" selected>Active</option>
                    {/if}
                    {else}
                    <option value="0" selected>Inactive</option>
                    <option value="1">Active</option>
                    {/else}
                </select>
            </span>
        </p>
        <p class="stdformbutton">
            <input name="submitEditClmenu" type="submit" value="Save" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>
<br clear="all" />
<script type="text/javascript" src="/public/js/custom/collectionmenu.js"></script>