<ul>
    <li class="current"><a href="/admin/" class="dashboard"><span>Dashboard</span></a></li>
    <li><a href="/admin/news/" class="tables"><span>News</span></a></li>
    <li><a href="/admin/announcement/" class="grid"><span>Announcement</span></a></li>
    <li><a href="/admin/photo/" class="media"><span>Photos</span></a></li>
    <li><a href="/admin/video/" class="media"><span>Videos</span></a></li>
    <li><a href="/admin/collection/" class="media"><span>Collections</span></a></li>
    <li><a href="/admin/collectionmenu/" class="media"><span>Collection Menu</span></a></li>
    <li><a href="/admin/partner/" class="contacts"><span>Partners</span></a></li>
    <li><a href="/admin/content/" class="editor"><span>Page content</span></a></li>
    {if $isAdmin || $isSuperAdmin}
    <li><a href="/admin/analytics/" class="charts"><span>Analytics</span></a></li>
    <li><a href="/admin/user/" class="users"><span>Users</span></a></li>
    <li><a href="/admin/system/" class="error"><span>System</span></a></li>
    {/if}
</ul>

