<ul class="maintabmenu">
    <li class="current"><a href="#">Pages</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle">
        <h2 class="form"><span>Edit {echo $content->pageName} Content</span></h2>
    </div>
    
    <form class="stdform stdform2" method="post" action="#" id="pageContentForm">
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        <p>
            <label>Section*</label>
            <span class="field">
                <select name="section" class="longinput">
                    {foreach $section in $sections}
                        {script $s=""}
                        {if $section->id == $content->sectionId}
                            {script $s = "selected"}
                        {/if}
                        <option value="{echo $section->id}" {echo $s}>{echo $section->title}</option>
                    {/foreach}
                </select>
            </span>
        </p>
        <p>
            <label>Page name*</label>
            <span class="field">
                <input type="text" name="page" required class="longinput" value="{echo $content->pageName}"/>
               {if isset($errors["pageName"])}
                    <label class="error">{echo join("<br/>", $errors["pageName"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Text*<small>Max. 50 000 characters</small></label>
            <span class="field">
                <textarea rows="20" name="text" id="ckeditor">{echo $content->body}</textarea>
                {if isset($errors["body"])}
                    <label class="error">{echo join("<br/>", $errors["body"])}</label>
                {/if}
            </span>
        </p>
        <p>
            <label>Active</label>
            <span class="field">
                <select name="active" class="longinput">
                    {if $content->active}
                    <option value="0">Inactive</option>
                    <option value="1" selected>Active</option>
                    {/if}
                    {else}
                    <option value="0" selected>Inactive</option>
                    <option value="1">Active</option>
                    {/else}
                </select>
            </span>
        </p>
        <p class="stdformbutton">
            <input name="submitEditContent" type="submit" value="Save" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>
</div>
<br class="clear-all" />