<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/photo/">Photo List</a></li>
    <li><a href="/admin/photo/add/">Add Photo</a></li>
    <li class="current"><a href="#">Edit Photo</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Edit Photo</span></h2>
    </div><!--contenttitle-->

    <form class="stdform stdform2" method="post" action="#">
        <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />
        <p>
            <label>Photo Name</label>
            <span class="field">
                {echo $photo->photoName}
            </span>
        </p>
        <p>
            <label>Description</label>
            <span class="field">
                <input type="text" name="description" class="longinput" value="{echo $photo->description}"/>
                {if isset($errors["description"])}
                <label class="error">
                    {echo join("<br/>", $errors["description"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Category</label>
            <span class="field">
                <input type="text" name="category" class="longinput" value="{echo $photo->category}"/>
                {if isset($errors["category"])}
                <label class="error">
                    {echo join("<br/>", $errors["category"])}
                </label>
                {/if}
            </span>
        </p>
        <p>
            <label>Section</label>
            <span class="field">
                {foreach $section in $sections}
                    {script $s = ""}
                    {if in_array($section->title, $photo->inSections)}
                        {script $s = "checked=\"checked\""}
                    {/if}
                    <span class="labeled-checkbox block">
                        <input type="checkbox" name="sections[]" {echo $s} value="{echo $section->id}">
                        {echo ucfirst($section->title)}
                    </span>
                {/foreach}
                {if isset($errors["sections"])}
                <label class="error">{echo join("<br/>", $errors["sections"])}</label>
                {/if}
            </span>
        </p>

        <p>
            <label>Priority<small>5 = highest priority</small></label>
            <span class="field">
                <select name="priority" >
                    {for $i=0 $i<6 $i++}
                        {if $i == $photo->priority}
                            <option value="$i" selected="selected">{echo $i}</option>
                        {/if}
                        {else}
                            <option value="$i">{echo $i}</option>
                        {/else}
                    {/for}
                </select>
            </span>
        </p>

        <p>
            <label>Active</label>
            <span class="field">
                <select name="active" class="longinput">
                    {if $photo->active}
                        <option value="0">Inactive</option>
                        <option value="1" selected>Active</option>
                    {/if}
                    {else}
                        <option value="0" selected>Inactive</option>
                        <option value="1">Active</option>
                    {/else}
                </select>
            </span>
        </p>

        <p class="stdformbutton">
            <input name="submitEditPhoto" type="submit" value="Save" class="submit radius2" />
        </p>
    </form>

</div>
<br class="clear-all"/>