<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="#">All Photos</a></li>
    <li><a href="/admin/photo/add/">Add Photo</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="image"><span>Photo List</span></h2>
    </div><!--contenttitle-->

    <input type="hidden" name="csrf" id="csrf" value="{echo $token}" />

    {if $isAdmin}
    <div class="tableoptions">
        <select class="radius3" name="selection">
            <option value="1">Selected</option>
            <option value="2">Current page</option>
        </select>
        <select class="radius3" name="action">
            <option value="activate">Activate</option>
            <option value="deactivate">Deactivate</option>
            <option value="delete">Delete</option>
        </select> &nbsp;
        <a class="btn btn_document ajax-massaction" href="/admin/photo/massaction/"><span>Execute</span></a>
    </div><!--tableoptions-->
    {/if}

    <table cellpadding="0" cellspacing="0" border="0" class="stdtable2">
        <colgroup>
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
            <col class="con0" /> <col class="con1" />
        </colgroup>
        <thead>
            <tr>
                <th class="head0 width50">ID</th>
                <td class="head1 width100">Thumb</td>
                <td class="head0">Name</td>
                <td class="head1">In Sections</td>
                <td class="head0">Size</td>
                <td class="head1">Resolution</td>
                <td class="head0">State</td>
                <td class="head1 width50">Priority</td>
                <td class="head0">Created</td>
                <td class="head1">&nbsp;</td>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th class="head0 width50">ID</th>
                <td class="head1 width100">Thumb</td>
                <td class="head0">Name</td>
                <td class="head1">In Sections</td>
                <td class="head0">Size</td>
                <td class="head1">Resolution</td>
                <td class="head0">State</td>
                <td class="head1 width50">Priority</td>
                <td class="head0">Created</td>
                <td class="head1">&nbsp;</td>
            </tr>
        </tfoot>
    </table>

    {if $isAdmin}
    <div class="tableoptions">
        <select class="radius3" name="selection">
            <option value="1">Selected</option>
            <option value="2">Current page</option>
        </select>
        <select class="radius3" name="action">
            <option value="activate">Activate</option>
            <option value="deactivate">Deactivate</option>
            <option value="delete">Delete</option>
        </select> &nbsp;
        <a class="btn btn_document ajax-massaction" href="/admin/photo/massaction/"><span>Execute</span></a>
    </div><!--tableoptions-->
    {/if}
</div>