<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/user/">User List</a></li>
    <li><a href="/admin/user/add/">Add User</a></li>
    <li class="current"><a href="#">Edit User</a></li>
    <li><a href="/admin/user/delete/{echo $user->id}">Delete User</a></li>
</ul>
<div class="content">
    <div class="contenttitle"><h2 class="form"><span>User Informations</span></h2></div><br />
    <form class="stdform stdform2" method="post" action="#">
        <p>
            <label>Firstname*</label>
            <span class="field">
                <input type="text" name="firstname" class="longinput" required value="{echo $user->firstname}"/>
            </span>
            {if isset($errors["firstname"])}
            <label class="error">
                {echo join("<br/>", $errors["firstname"])}
            </label>
            {/if}
        </p>
        <p>
            <label>Lastname*</label>
            <span class="field">
                <input type="text" name="lastname" class="longinput" required value="{echo $user->lastname}"/>
            </span>
            {if isset($errors["lastname"])}
            <label class="error">
                {echo join("<br/>", $errors["lastname"])}
            </label>
            {/if}
        </p>
        <p>
            <label>Email*</label>
            <span class="field">
                <input type="email" name="email" class="longinput" required value="{echo $user->email}"/>
            </span>
            {if isset($errors["email"])}
            <label class="error">
                {echo join("<br/>", $errors["email"])}
            </label>
            {/if}
        </p>
        <p>
            <label>Password</label>
            <span class="field">
                <input type="password" name="password" class="longinput" value=""/>
            </span>
            {if isset($errors["password"])}
            <label class="error">
                {echo join("<br/>", $errors["password"])}
            </label>
            {/if}
        </p>
        <p>
            <label>Confirm password</label>
            <span class="field">
                <input type="password" name="password2" class="longinput" value=""/>
            </span>
            {if isset($errors["password2"])}
            <label class="error">
                {echo join("<br/>", $errors["password2"])}
            </label>
            {/if}
        </p>
        {if ($superadmin)}
        <p>
            <label>Role</label>
            <span class="field">
                <select name="role" class="longinput">
                    {if $user->role == "role_superadmin"}
                    <option value="role_publisher">Publisher</option>
                    <option value="role_admin">Admin</option>
                    <option value="role_superadmin" selected>Super Admin</option>
                    {/if}
                    {elseif $user->role == "role_admin"}
                    <option value="role_publisher">Publisher</option>
                    <option value="role_admin" selected>Admin</option>
                    <option value="role_superadmin">Super Admin</option>
                    {/elseif}
                    {else}
                    <option value="role_publisher" selected>Publisher</option>
                    <option value="role_admin">Admin</option>
                    <option value="role_superadmin">Super Admin</option>
                    {/else}
                </select>
            </span>
            {if isset($errors["role"])}
            <label class="error">
                {echo join("<br/>", $errors["role"])}
            </label>
            {/if}
        </p>
        <p>
            <label>Active</label>
            <span class="field">
                <select name="active" class="longinput">
                    {if $user->active}
                    <option value="0">Inactive</option>
                    <option value="1" selected>Active</option>
                    {/if}
                    {else}
                    <option value="0" selected>Inactive</option>
                    <option value="1">Active</option>
                    {/else}
                </select>
            </span>
        </p>
        {/if}
        <p>
            <span class="stdformbutton">
                <input type="submit" name="submitEditUser" value="Save changes" />
            </span>
        </p>
    </form>
</article>