<ul class="maintabmenu multipletabmenu">
    <li class="current"><a href="/admin/system/">Main</a></li>
    <li><a href="/admin/system/settings/">Settings</a></li>
    {if $isSuperAdmin}<li><a href="/admin/system/showAdminLog/">Admin log</a></li>{/if}
</ul><!--maintabmenu-->
<div class="content">

    <div class="one_fifth">
        <div class="contenttitle"><h2 class="form"><span>Clear cache</span></h2></div>
        <form class="stdform stdform2" method="post" action="/admin/system/clearCache/">
            <input type="hidden" name="tk" id="tk" value="{echo $token}" />
            <p class="stdformbutton">
                <input name="clearCache" type="submit" value="Clear cache" class="submit radius2" />
            </p>
        </form>
    </div>
    <div class="one_fifth">
        <div class="contenttitle"><h2 class="form"><span>Database backup</span></h2></div>
        <form class="stdform stdform2" method="post" action="/admin/system/createDatabaseBackup/">
            <input type="hidden" name="tk" id="tk" value="{echo $token}" />
            <p class="stdformbutton">
                <input name="createBackup" type="submit" value="Create backup" class="submit radius2" />
            </p>
        </form>
    </div>
    <div class="one_fifth">
        <div class="contenttitle"><h2 class="form"><span>Archivate older news</span></h2></div>
        <form class="stdform stdform2" method="post" action="/admin/system/archivateNews/">
            <input type="hidden" name="tk" id="tk" value="{echo $token}" />
            <p class="stdformbutton">
                <input name="archivateNews" type="submit" value="Archivate" class="submit radius2" />
            </p>
        </form>
    </div>

    <div class="one_fifth">
        <div class="contenttitle"><h2 class="form"><span>Change Application Status</span></h2></div>
        <form class="stdform stdform2" method="post" action="/admin/system/changeApplicationStatus/">
            <input type="hidden" name="tk" id="tk" value="{echo $token}" />
            <p class="stdformbutton">
                <input name="changeStatus" type="submit" value="{echo $appstatus}" class="submit radius2" />
            </p>
        </form>
    </div>
    
    <br clear="all" />
</div><!--widgetcontent-->

<br clear="all" />