<ul class="maintabmenu multipletabmenu">
    <li><a href="/admin/system/">Main</a></li>
    <li class="current"><a href="#">Settings</a></li>
    <li><a href="/admin/system/showadminlog/">Admin log</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <div class="contenttitle radiusbottom0">
        <h2 class="table"><span>Application Settings</span></h2>
    </div><!--contenttitle-->

    <form class="stdform stdform2" method="post" action="#" >
        <input type="hidden" name="tk" id="tk" value="{echo $token}" />
        {if !empty($config)}
            {foreach $conf in $config}
            <p>
                <label>{echo $conf->getTitle()}</label>
                <span class="field">
                    {if strlen($conf->getValue()) > 200}
                        <textarea name="{echo $conf->getXkey()}" rows="3" class="longinput">{echo $conf->getValue()}</textarea>
                    {/if}
                    {else}
                        <input type="text" class="longinput" name="{echo $conf->getXkey()}" value="{echo $conf->getValue()}" />
                    {/else}
                    
                    {if isset($errors[$conf->getXkey()])}
                        <label class="error">{echo join("<br/>", $errors[$conf->getXkey()])}</label>
                    {/if}
                </span>
            </p>
            {/foreach}
        {/if}

        <p class="stdformbutton">
            <input name="submitEditSet" type="submit" value="Save" class="submit radius2" />
            <input type="reset" class="reset radius2" value="Reset" />
        </p>
    </form>

</div>
<br class="clear-all"/>