<script type="text/javascript" src="/public/js/custom/dashboard.js"></script>
<ul class="maintabmenu">
    <li class="current"><a href="/admin/">Dashboard</a></li>
</ul><!--maintabmenu-->

<div class="content">
    <ul class="widgetlist">
        <li><a href="/admin/news/add/" class="events">New News</a></li>
        <li><a href="/admin/collection/" class="upload">Collection</a></li>
        <li><a href="/admin/photo/add/" class="upload">Upload Photo</a></li>
        <li><a href="/admin/analytics/" class="events">Analytics</a></li>
    </ul>

    <br clear="all" /><br />

    <div class="one_half">
        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Latest News</span></h2></div>
            <div class="widgetcontent announcement">
                {if !empty($latestnews)}
                    {foreach $news in $latestnews}
                        <p>
                            <span class="radius2">Title: {echo $news->getTitle()}</span>
                            <span class="radius2">Created: {echo $news->getCreated()}</span>
                            <br/><br/>
                            {echo $news->shortBody}
                        </p>
                        <hr/>
                    {/foreach}
                {/if}
                {else}
                    <p>No news</p>
                {/else}
            </div><!--widgetcontent-->
        </div><!--widgetbox-->

    </div><!--one_half-->

    <div class="one_half last">

        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Latest Announcement</span></h2></div>
            <div class="widgetcontent announcement">
                {if !empty($activeannounc)}
                    {foreach $announc in $activeannounc}
                        <p>
                            <span class="radius2">Title: {echo $announc->getTitle()}</span>
                            <span class="radius2">Created: {echo $announc->getCreated()}</span><br/><br/>";
                        </p>
                        <hr/>
                    {/foreach}
                {/if} 
                {else}
                    <p>No announcement</p>
                {/else}
            </div><!--widgetcontent-->
        </div><!--widgetbox-->

    </div><!--one_half-->

    <br clear="all" /><br />

    <div class="one_half">

        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Partners</span></h2></div>
            <div class="widgetcontent padding0 statement">
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" />
                        <col class="con1" />
                        <col class="con0" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0">Name</th>
                            <th class="head1">Logo</th>
                            <th class="head0">Webpage</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if !empty($partnerlist)}
                            {foreach $partner in $partnerlist}
                                <tr>
                                    <td>{echo $partner->getTitle()}</td>
                                    <td><img src="{echo $partner->getLogo()}" alt="" height="50px" /></td>
                                    <td>
                                        <a href="{echo $partner->getWeb()}" target="_blank">
                                            {echo $partner->getWeb()}
                                        </a>
                                    </td>
                                </tr>
                            {/foreach}
                        {/if} 
                    </tbody>
                </table>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->                        
    </div><!--one_half-->

    <div class="one_half last">

        <div class="widgetbox">
            <div class="title"><h2 class="tabbed"><span>Collection List</span></h2></div>
            <div class="widgetcontent padding0 statement">
                <table cellpadding="0" cellspacing="0" border="0" class="stdtable">
                    <colgroup>
                        <col class="con0" />
                        <col class="con1" />
                        <col class="con0" />
                    </colgroup>
                    <thead>
                        <tr>
                            <th class="head0">Title</th>
                            <th class="head1">Photographer</th>
                            <th class="head0">Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {if !empty($collectionlist)}
                            {foreach $collection in $collectionlist}
                                <tr>
                                    <td>
                                        <a href="/admin/collection/detail/{echo $collection->getId()}">{echo $collection->getTitle()}</a>
                                    </td>
                                    <td>{echo $collection->getPhotographer()}</td>
                                    <td>{echo $collection->getDate()}</td>
                                </tr>
                            {/foreach}
                        {/if} 
                    </tbody>
                </table>
            </div><!--widgetcontent-->
        </div><!--widgetbox-->                        
    </div><!--one_half-->

    <br clear="all" /><br />

</div><!--content-->