<div class="section-content-text">
    {echo html_entity_decode($text->body)}
</div>

{if ($photos && !empty($photos))}
    <div class="section-content-photos">
        {foreach $photo in $photos}
            <a href="{echo $photo->imgMain}" class="highslide" 
               title="{echo $photo->description}" onclick="return hs.expand(this, configbio)">
                <img src="{echo $photo->imgThumb}" alt="Marko.in"/>
            </a>
        {/foreach}
    </div>
{/if}

{if ($videos && !empty($videos))}
    <div class="section-content-videos">
        {foreach $video in $videos}
            <iframe width="{echo $video->width}" height="{echo $video->height}" 
                    src="{echo $video->path}" frameborder="0" allowfullscreen></iframe>
        {/foreach}
    </div>
{/if}