<div class="section-content-text">
    {echo html_entity_decode($text->body)}
</div>
{if ($collectionlist && !empty($collectionlist))}
    <div class="section-content-collectionList">
        {foreach $item in $collectionlist}
            <a href="#" class="collectionLink ajaxLink" id="show_design_{echo $item->urlKey}"> 
                {if $item->customName == ""}{echo ucfirst($item->title)}{/if}
                {else}{echo ucfirst($item->customName)}{/else}</a>
            <br/>
        {/foreach}
    </div>
{/if}

{if ($photos && !empty($photos))}
    <div class="section-content-photos">
        {foreach $photo in $photos}
            <a href="{echo $photo->path}" class="highslide" 
               title="{echo $photo->photoName}" onclick="return hs.expand(this, configbio)">
                <img src="{echo $photo->thumbPath}" alt="Marko.in"/>
            </a>
        {/foreach}
    </div>
{/if}

{if ($videos && !empty($videos))}
    <div class="section-content-videos">
        {foreach $video in $videos}
            <iframe width="{echo $video->width}" height="{echo $video->height}" 
                    src="{echo $video->path}" frameborder="0" allowfullscreen></iframe>
        {/foreach}
    </div>
{/if}