<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="cs" />
        {if $env == "live"}<meta http-equiv="CACHE-CONTROL" content="public, max-age=10800">{/if}
        {else}<meta http-equiv="CACHE-CONTROL" content="no-store">{/else}

        <meta name="viewport" content="width=device-width, maximum-scale=2.0, minimum-scale=1.0, initial-scale=1.0" />
        <meta name="keywords" content="{echo $metakeywords}" />
        <meta name="author" content="Tomas Hodan" />
        <meta name="robots" content="{echo $metarobots}" />
        <meta name="description" content="{echo $metadescription}" />
        <meta name="revisit-after" content="4 Days" />
        <meta name="distribution" content="global"/>
        <meta name="language" content="czech" />

        {if isset($article)}
        <meta property="og:title" content="{echo $metatitle}" />
        <meta property="og:type" content="{echo $metaogtype}" />
        <meta property="og:url" content="{echo $metaogurl}" />
        <meta property="og:image" content="{echo $metaogimage}" />
        <meta property="og:description" content="{echo $metadescription}" />
        <meta property="og:site_name" content="{echo $metaogsitename}" />
        <meta property="article:published_time" content="{echo $artcreated}" />
        <meta property="article:modified_time" content="{echo $artmodified}" />
        {/if}{else}
        <meta property="og:url" content="{echo $metaogurl}" />
        <meta property="og:title" content="{echo $metatitle}" />
        <meta property="og:description" content="{echo $metadescription}" />
        <meta property="og:type" content="{echo $metaogtype}" />
        <meta property="og:site_name" content="{echo $metaogsitename}" />
        {/else}

        <link href="/public/images/markoin_favicon.jpg" rel="icon" type="image/x-icon"/>
        <link href="/public/css/reset.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/styles.min.css" media="screen" rel="stylesheet" type="text/css" />
        <!--[if IE]> <link href="/public/css/stylesIE.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
        <link href="/public/css/plugins/highslide.min.css" media="screen" rel="stylesheet" type="text/css" />
        <!--[if lt IE 7]> <link href="/public/css/plugins/highslide-ie6.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->

        <!--[if lt IE 9]><script type="text/javascript" src="/public/js/plugins/html5.js"></script><![endif]-->
        <script type="text/javascript" src="/public/js/plugins/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="/public/js/plugins/jquery-ui-1.10.4.custom.min.js"></script>

        <title>{echo $metatitle}</title>
    </head>
    <body lang="cs">
        <div id="fb-root"></div>
        <script type="text/javascript" src="/public/js/custom/fbshare.js"></script>

        <div id="page">
            {if !isset($hidetop)}<div id="temptopdiv"></div>{/if}
            <div id="navi">
                <ul>
                    <li id="navi_news"><a href="#"><h1>Novinky</h1></a></li>
                    <li id="navi_provas"><a href="#"><h1>Pro Vás</h1></a></li>
                    <li id="navi_design"><a href="#"><h1>Design</h1></a></li>
                    <li id="navi_styling"><a href="#"><h1>Styling</h1></a></li>
                    <li id="navi_partners"><a href="#"><h1>Partneři</h1></a></li>
                    <li id="navi_contact"><a href="#"><h1>Kontakt</h1></a></li>
                </ul>
            </div>

            <div id="main">
                <div id="news" {if !isset($shownews)} class="nodisplay" {/if}>
                     <a href="#" class="close">Zavřít</a>
                    <div class="content">{if isset($shownews)}{yield action}{/if}</div>
                    <div class="paginationCont">
                        <ul class="pagination">
                            {for $i=1 $i<=$newspagecount $i++}
                            <li><a title="{echo $i}" href="#">$i</a></li>
                            {/for}
                        </ul>
                    </div>
                </div>

                <div id="news-detail" {if !isset($shownd)} class="nodisplay" {/if}>
                     <a href="#" class="close">Zavřít</a>
                    <div class="content">{if isset($shownd)}{yield action}{/if}</div>
                </div>

                <div id="provas" {if !isset($showcust)} class="nodisplay" {/if}>
                     <a href="#" class="close">Zavřít</a>       
                    <div class="content">{if isset($showcust)}{yield action}{/if}</div>
                </div>

                <div id="design" {if !isset($showdesign)} class="nodisplay" {/if}>
                     <a href="#" class="close">Zavřít</a>
                    <div class="content">{if isset($showdesign)}{yield action}{/if}</div>
                </div>

                <div id="styling" {if !isset($showstyling)} class="nodisplay" {/if}>
                     <a href="#" class="close">Zavřít</a>       
                    <div class="content">{if isset($showstyling)}{yield action}{/if}</div>
                </div>

                <div id="contact" {if !isset($showcontact)} class="nodisplay" {/if}>
                     <a href="#" class="close">Zavřít</a>
                    <div class="content">{if isset($showcontact)}{yield action}{/if}</div>
                </div>

                <div id="portfolio" class="nodisplay">
                    <a href="#" class="close">Zavřít</a>
                    <div class="content"></div>
                </div>

                <div id="collection" class="nodisplay">
                    <a href="#" class="close">Zavřít</a>
                    <div class="content"></div>
                </div>

                <div id="bio" {if !isset($showbio)} class="nodisplay" {/if}>
                     <a href="#" class="close">Zavřít</a>       
                    <div class="content">{if isset($showbio)}{yield action}{/if}</div>
                </div>

                <div id="partners" {if !isset($showpartners)} class="nodisplay" {/if}>
                     <a href="#" class="close">Zavřít</a>
                    <div class="content">{if isset($showpartners)}{yield action}{/if}</div>
                </div>
                
                {if (!empty($announcement))}
                    <div id="announcement">
                        <a href="#" class="close-announcement">Zavřít</a>
                        <div class="text">
                            <span class="stencilla">{echo $announcement->title}</span><br/><br/>
                            {echo $announcement->body}<br/>
                            <br/>
                            <span class="ancSignature">{echo $announcement->signature}</span>
                        </div>
                    </div>
                {/if}
            </div>

            <div id="spacer"></div>
            <div class="main-fb-like">
                <iframe src="//www.facebook.com/plugins/like.php?href=http://www.facebook.com/MarkoIn&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=21" 
            scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:21px;" allowTransparency="true"></iframe>
            </div>
            
            <div id="footer">
                2012 Marko.in Designed by Marko.in Created by <a class="mailto" href="mailto:hodan.tomas@gmail.com">Tomáš & Lukáš Hodáň</a>
            </div>
        </div>

        <script type="text/javascript" src="/public/js/custom/navigation.js"></script>
        <script type="text/javascript" src="/public/js/plugins/highslide-with-gallery.min.js"></script>
        <script type="text/javascript" src="/public/js/plugins/highslide.config.js"></script>
        <script type="text/javascript" src="/public/js/custom/pagination.js"></script>

        <!-- Piwik -->
        {if $env == "live"}
        <script type="text/javascript">
            var pkBaseURL = (("https:" == document.location.protocol) ? "https://marko.in/piwik/" : "http://marko.in/piwik/");
            document.write(unescape("%3Cscript src=\"" + pkBaseURL + "piwik.js\" type=\"text/javascript\"%3E%3C/script%3E"));
        </script>
        <script type="text/javascript">
            try {
                var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 1);
                piwikTracker.trackPageView();
                piwikTracker.enableLinkTracking();
            } catch (err) {
            }
        </script>
        <noscript><p><img src="http://marko.in/piwik/piwik.php?idsite=1" style="border:0" alt="" /></p></noscript>
        {/if}
        <!-- End Piwik Tracking Code -->
    </body>
</html>