<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="cs" />
        <meta http-equiv="CACHE-CONTROL" content="public">
        <meta name="viewport" content="width=device-width, maximum-scale=2.0, minimum-scale=1.0, initial-scale=1.0" />
        <meta name="keywords" content="marko.in, styling, design, fashion, Marko Lopatić, Marko Lopatič" />
        <meta name="author" content="Tomas Hodan" />
        <meta name="robots" content="INDEX,NOFOLLOW" />
        <meta name="description" content="Marko.in" />

        <link href="/public/images/markoin_favicon.jpg" rel="icon" type="image/x-icon"/>
        <link href="/public/css/reset.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/plugins/smoothness/jquery-ui-1.10.4.custom.min.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/styles.css" media="screen" rel="stylesheet" type="text/css" />
        <!--[if IE]> <link href="/public/css/stylesIE.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
        <link href="/public/css/plugins/highslide.min.css" media="screen" rel="stylesheet" type="text/css" />
        <!--[if lt IE 7]> <link href="/public/css/plugins/highslide-ie6.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->

        <!--[if lt IE 9]><script type="text/javascript" src="/public/js/plugins/html5.js"></script><![endif]-->
        <script type="text/javascript" src="/public/js/plugins/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="/public/js/plugins/jquery-ui-1.10.4.custom.min.js"></script>

        <title>Marko.in</title>
    </head>
    <body lang="cs">
        <div id="page">
            {if !isset($hidetop)}<div id="temptopdiv"></div>{/if}
            <div id="navi">
                <ul>
                    <li id="navi_news"><a href="#"><h1>Novinky</h1></a></li>
                    <li id="navi_bio"><a href="#"><h1>Bio</h1></a></li>
                    <li id="navi_design"><a href="#"><h1>Design</h1></a></li>
                    <li id="navi_styling"><a href="#"><h1>Styling</h1></a></li>
                    <li id="navi_partners"><a href="#"><h1>Partneři</h1></a></li>
                    <li id="navi_contact"><a href="#"><h1>Kontakt</h1></a></li>
                </ul>
            </div>

            <div id="main">

                <div id="news" class="nodisplay">
                    <a href="#" class="close">Zavřít</a>
                    <div class="content"></div>
                </div>

                <div id="news-detail" {if !isset($shownd)} class="nodisplay" {/if}>
                    <a href="#" class="close">Zavřít</a>
                    <div class="content">{if isset($shownd)}{yield action}{/if}</div>
                </div>

                <div id="bio" {if !isset($showbio)} class="nodisplay" {/if}>
                    <a href="#" class="close">Zavřít</a>       
                    <div class="content">{if isset($showbio)}{yield action}{/if}</div>
                </div>

                <div id="design" {if !isset($showdesign)} class="nodisplay" {/if}>
                    <a href="#" class="close">Zavřít</a>
                    <div class="content">{if isset($showdesign)}{yield action}{/if}</div>
                </div>

                <div id="styling" {if !isset($showstyling)} class="nodisplay" {/if}>
                    <a href="#" class="close">Zavřít</a>       
                    <div class="content">{if isset($showstyling)}{yield action}{/if}</div>
                </div>

                <div id="contact" {if !isset($showcontact)} class="nodisplay" {/if}>
                    <a href="#" class="close">Zavřít</a>
                    <div class="content">{if isset($showcontact)}{yield action}{/if}</div>
                </div>

                <div id="portfolio" class="nodisplay">
                    <a href="#" class="close">Zavřít</a>
                    <div class="content"></div>
                </div>

                <div id="collection" class="nodisplay">
                    <a href="#" class="close">Zavřít</a>
                    <div class="content"></div>
                </div>

                <div id="partners" {if !isset($showpartners)} class="nodisplay" {/if}>
                    <a href="#" class="close">Zavřít</a>
                    <div class="content">{if isset($showpartners)}{yield action}{/if}</div>
                </div>
            </div>

            <div id="spacer"></div>
            <div id="footer">
                2012 Marko.in vytvořil <a class="mailto" href="mailto:hodan.tomas@gmail.com">Tomáš & Lukáš Hodáň</a>
            </div>

        </div>

        <script type="text/javascript" src="/public/js/custom/menu.js"></script>
        <script type="text/javascript" src="/public/js/plugins/highslide-with-gallery.min.js"></script>
        <script type="text/javascript" src="/public/js/plugins/highslide.config.js"></script>
        <script type="text/javascript" src="/public/js/custom/pagination.js"></script>

        <!-- Piwik --> 
        
        <!-- End Piwik Tracking Code -->
    </body>
</html>