<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="cs" />
        <meta http-equiv="CACHE-CONTROL" content="public">
        <meta name="viewport" content="width=device-width, maximum-scale=2.0, minimum-scale=1.0, initial-scale=1.0" />
        <meta name="keywords" content="{echo $metakeywords}" />
        <meta name="author" content="Tomas Hodan" />
        <meta name="robots" content="{echo $metarobots}" />
        <meta name="description" content="{echo $metadescription}" />

        <link href="/public/images/markoin_favicon.jpg" rel="icon" type="image/x-icon"/>
        <link href="/public/css/reset.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/plugins/smoothness/jquery-ui-1.10.4.custom.min.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="/public/css/mobile.css" media="screen" rel="stylesheet" type="text/css" />
        <!--[if IE]> <link href="/public/css/stylesIE.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->
        <link href="/public/css/plugins/highslide.min.css" media="screen" rel="stylesheet" type="text/css" />
        <!--[if lt IE 7]> <link href="/public/css/plugins/highslide-ie6.css" media="screen" rel="stylesheet" type="text/css" /><![endif]-->

        <!--[if lt IE 9]><script type="text/javascript" src="/public/js/plugins/html5.js"></script><![endif]-->
        <script type="text/javascript" src="/public/js/plugins/jquery-1.11.1.min.js"></script>
        <script type="text/javascript" src="/public/js/plugins/jquery-ui-1.10.4.custom.min.js"></script>

        <title>Marko.in</title>
    </head>
    <body lang="cs">
        <div id="page">
            {if !isset($hidetop)}<div id="temptopdiv"></div>{/if}
            <div id="navi">
                <ul>
                    <li id=""><a href="#"><h1></h1></a></li>
                </ul>
                <select>
                    <option value="navi_news"><h1>Novinky</h1></option>
                    <option value="navi_provas"><h1>Pro Vás</h1></option>
                    <option value="navi_design"><h1>Design</h1></option>
                    <option value="navi_styling"><h1>Styling</h1></option>
                    <option value="navi_partners"><h1>Partneři</h1></option>
                    <option value="navi_contact"><h1>Kontakt</h1></option>
                </select>
            </div>

            <div id="main">

                <div id="news" {if !isset($shownews)} class="nodisplay" {/if}>
                    <a href="#" class="close">Zavřít</a>
                    <div class="content">{if isset($shownews)}{yield action}{/if}</div>
                    <div class="paginationCont">
                        <ul class="pagination">
                            {for $i=1 $i<=$newspagecount $i++}
                            <li><a title="{echo $i}" href="#">$i</a></li>
                            {/for}
                        </ul>
                    </div>
                </div>

                <div id="news-detail" {if !isset($shownd)} class="nodisplay" {/if}>
                    <a href="#" class="close">Zavřít</a>
                    <div class="content">{if isset($shownd)}{yield action}{/if}</div>
                </div>

                <div id="showaction" {if !isset($showaction)} class="nodisplay" {/if}>
                    <a href="#" class="close">Zavřít</a>       
                    <div class="content">{if isset($showaction)}{yield action}{/if}</div>
                </div>

                <div id="collection" class="nodisplay">
                    <a href="#" class="close">Zavřít</a>
                    <div class="content"></div>
                </div>
            </div>

            <div id="spacer"></div>
            <div id="footer">
                2012 Marko.in Designed by Marko.in Created by <a class="mailto" href="mailto:hodan.tomas@gmail.com">Tomáš & Lukáš Hodáň</a>
            </div>
        </div>

        <script type="text/javascript" src="/public/js/custom/navigation-tablet.js"></script>
        <script type="text/javascript" src="/public/js/plugins/highslide-with-gallery.min.js"></script>
        <script type="text/javascript" src="/public/js/plugins/highslide.config.js"></script>
        <script type="text/javascript" src="/public/js/custom/pagination.js"></script>

        <!-- Piwik --> 
        
        <!-- End Piwik Tracking Code -->
    </body>
</html>